### ISSUE TITLE
Blank Screen on Logout

### ISSUE THREAD

**Issue by GaneshKandu** [bigprof/Resources-Utilization-Viewer--RUView-#1]
Hi My Name is Ganesh Kandu
I Have Installed RUView,
and I am getting Blank screen when I am logout from this url "<path>/admin/pageHome.php"

**Comment by GaneshKandu** [comment]
@GaneshKandu
GaneshKandu commented a minute ago

Hi My Name is Ganesh Kandu
I Have Installed RUView v5.41,
and I am getting Blank screen when I am logout from this url "/admin/pageHome.php"

**Comment by bigprof** [comment]
Please specify the browser you are using and which version. I was unable to reproduce this issue on Firefox (version 41) not on Chrome (version 46).

**Comment by GaneshKandu** [comment]
FireFox and Mozilla Developers V 41.0.2
File Version 41.0.2.5765

I am Tried in Chrome its working in Chrome
but Not Working in FireFox and Mozilla Developers V 41.0.2

**Comment by bigprof** [comment]
Thanks for the update. I haven't been able to reproduce this issue so far on Firefox. Since you reported it working on Chrome, I'll close the issue for now.
